
create sequence REMEK_SEQ start 10;

create table appuser
(
    id                      int8 generated by default as identity,
    username                varchar(32) not null,
    firstname               varchar(64) not null,
    lastname                varchar(64) not null,
    password                varchar(255) not null,
    lastpracticedate        date,
    numberofconsecutivedays int4,
    numberofpracticedays    int4,
    iconimgname             varchar(255),
    primary key (id)
);

create table reward
(
    id                      int8 generated by default as identity,
    name                    varchar(255) not null,
    type                    varchar(255) not null,
    number_to_achieve       int8 not null,
    img_name                varchar(255),
    primary key (id)
);

create table appuser_reward
(
    appuser_id              int8 not null,
    reward_id               int8 not null,
    constraint appuser_reward_appuser_fk foreign key (appuser_id) references appuser,
    constraint appuser_reward_reward_fk foreign key (reward_id) references reward
);

create table eye_practice
(
    id                      int8 generated by default as identity,
    name                    varchar(255) not null,
    type                    varchar(255) not null,
    recommended_time        int4,
    disclaimer              text,
    primary key (id)
);

create table eye_exercise
(
    id                      int8 generated by default as identity,
    eye_practice_id         int8 not null,
    order_number            int4 not null,
    name                    varchar(255) not null,
    text                    text not null,
    primary key (id),
    constraint eye_exercise_eye_practice_fk foreign key (eye_practice_id) references eye_practice
);

create table eye_exercise_images
(
    id                      int8 generated by default as identity,
    eye_exercise_id         int8 not null,
    order_number            int4 not null,
    img_name                varchar(255) not null,
    primary key (id),
    constraint eye_exercise_images_eye_exercise_fk foreign key (eye_exercise_id) references eye_exercise
);



